In [1]:
import sys

mpath = '/home/dbcloud/ym/CSPG/ANNS/modules'

if mpath not in sys.path:
  sys.path.append(mpath)

import anns
import numpy as np

In [2]:
from binary_io import  *

base = "/var/lib/docker/anns/dataset/sift1m/base.fvecs"
query = "/var/lib/docker/anns/query/sift1m/query.fvecs"
gt = "/var/lib/docker/anns/query/sift1m/gt.ivecs"

base = fvecs_read(base)
query = fvecs_read(query)
gt = ivecs_read(gt)

base, query, gt

(array([[ 0., 16., 35., ..., 25., 23.,  1.],
        [14., 35., 19., ..., 11., 21., 33.],
        [ 0.,  1.,  5., ...,  4., 23., 10.],
        ...,
        [34.,  8., 32., ..., 11.,  2.,  6.],
        [14.,  7.,  5., ..., 28., 16., 38.],
        [54., 51., 15., ...,  4., 17., 32.]], dtype=float32),
 array([[  1.,   3.,  11., ...,  42.,  48.,  11.],
        [ 40.,  25.,  11., ...,   3.,  19.,  13.],
        [ 28.,   4.,   3., ...,   2.,  54.,  47.],
        ...,
        [  0.,  15.,  64., ...,   3.,  62., 118.],
        [131.,   2.,   0., ...,   7.,   0.,   0.],
        [ 23.,   0.,   0., ...,  79.,  16.,   4.]], dtype=float32),
 array([[932085, 934876, 561813, ..., 398306, 931721, 989762],
        [413247, 413071, 706838, ..., 855176, 846198, 987074],
        [669835, 408764, 408462, ..., 310475, 971815, 937903],
        ...,
        [123855, 123351, 534149, ...,  90175, 685486, 416474],
        [755327, 755323, 840765, ..., 595134, 601257, 172180],
        [874343, 464509, 413340, ...

In [3]:
nb, d = base.shape
nq, _ = query.shape
_, ngt = gt.shape

nb, d, nq, ngt

(67000, 128, 10000, 100)

In [4]:
m = 2
threads = 24
k = 10

base = base.flatten().tolist()
query = query.flatten().tolist()
gt = gt.flatten().tolist()

In [5]:
index = anns.CSPG_HNSW_FLOAT(d, m)

index.build(base, threads, [32, 128, 0.5])

In [6]:
knn = index.search(query, k, threads, ef1 = 1, ef2 = 128)

In [7]:
print(anns.get_recall(k, ngt, gt, knn))

0.09764
